name: Build

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-10.15

    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          xcodebuild -configuration ${{ matrix.configuration }} build | xcpretty && exit ${PIPESTATUS[0]}
